version: '3'

services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - 8081:80
    volumes:
      - ./web:/var/www/html

  db:
    image: mysql:5.7
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
# volumes:
#   db_data:
